Change import cache-keys to reading with fs
serlo/api.serlo.org-cache-worker pull request #22
Opened 2021-01-15 21:35 UTC by hugotiburtino

2021-01-18 08:39 UTC, kulla requested changes
Just minor change requests

2021-01-18 08:39 UTC, kulla commented on src/index.ts
> +  }
```suggestion
  let pagination = process.env.PAGINATION === undefined ?  undefined : parseInt(process.env.PAGINATION)

```

2021-01-18 08:39 UTC, kulla commented on src/index.ts
>    if (pagination !== undefined && pagination <= 0) {
```suggestion
  if (Number.isNaN(pagination)) {
    pagination = undefined
  }
  if (pagination !== undefined && pagination <= 0) {
```

2021-01-18 21:24 UTC, hugotiburtino commented
@kulla changes made

2021-02-10 16:20 UTC, kulla approved these changes

2021-02-10 16:21 UTC, merged